### ISSUE TITLE
[request] add PSG Covid utils to the list?

### ISSUE THREAD

**Issue by PySimpleGUI** [Uniminin/Educational-Links#1]
This was just published in the latest PyCoders

https://github.com/PySimpleGUI/PySimpleGUI-COVID19

And of course there are a ton of educational things, demo programs, documentation, on the PySimpleGUI site - http://www.PySimpleGUI.org (docs)   http://www.PySimpleGUI.com (GitHub)
Not sure if that fits any categories though... but I'll take free publicity anywhere ;-)

**Comment by Uniminin** [comment]
thanku
